server:
  address: 192.168.31.101
  port: 9099

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.address}:3306/db_rasta?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: RastaHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: ${server.address}
    port: 6379
    password: 123456
  rabbitmq:
    host: ${server.address}
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: r_
    banner: off
  type-handlers-package: cn.dlmyl.rasta.infra.support.mybatis.handler

logging:
  config: classpath:logback-spring.xml
  level:
    root: info

rasta:
  default:
    domain: ${server.address}:${server.port}
  sql:
    show: false
  code:
    batch: 100
  error:
    page:
      url: https://www.baidu.com/404.html
  exclude:
    uris: /env,/index.html,/index.jsp
  snowflake:
    data:
      center:
        id: 1
    worker:
      id: 1